export default [
    {
        "id": "Aquarius",
        "range": "January 20 - February 18",
        "horoscopes": "You love having fun with other people as much as anyone, but remember that you have the right to privacy too. If you just aren't feeling up to a night out or can't bear to organize another group outing, then don't. Say no to that next invitation and tell everyone to have fun without you. There's nothing wrong with spending some time alone. In fact, it's healthy. It will help you get more centered and give everyone else a chance to miss you for a while!",
        "love": "You will find yourself opening yourself up emotionally to others. It would be a great time to hold a virtual party or just invite a small group of friends around for a get-together, if possible. It would also be a good time to start communicating with some new people. Love thrives in new conditions and with people who are original and refreshingly unembarrassed about themselves.",
        "money": "The planets want to make you beautiful and magnetic, pulling people, situations, and opportunities to you so you can fulfill your goals and dreams this week. They ask you to build self-confidence and adjust the way you put yourself into the world. The more you open up to learning from new experiences, the easier it will be to access ",
    },
    {
        "id": "Aries",
        "range": "March 21 - April 19",
        "horoscopes": "This is not the time to leap outside your comfort zone. If you aren't comfortable right now, you won't be happy. Your emotions are driving you to make hasty decisions that might not be in your best interests in the long run, so resist the urge to start something new. Later, you can start pushing yourself to be more bold, more emotional, whatever. That's always invigorating, but it can also be dangerous. Just keep yourself busy with your daily routine for now.",
        "love": "You will be consumed with the desire to explore on a social level. You could make the decision to attend a small party that you may have previously thought about avoiding. Love may be found in precisely whatever kinds of social situations are possible to participate in, and not by staying around in the same circles of people. And anyway, you need someone else to listen to your old jokes.",
        "money": "This week is about visibility. If you've felt invisible over the past few months, you're definitely in full view now. Others can't help but hear everything you say and honor your opinions. This is especially true since aspects are affecting your social networks. It seems everyone already knows about your good work. Regale them with stories of your recent antics and future plans. Money is a sure thing.",
    },
    {
        "id": "Cancer",
        "range": "June 22 - July 22",
        "horoscopes": "If you're worried about a friend, your concerns could be unwarranted right now. Don't act on your feelings just yet. You can't get involved with situations you're unsure of, and you can't be a hundred percent certain that what you fear is true. Just let things be for a while, and don't push too hard. You might think you're acting as a compassionate friend, but they might think you're meddling in their life too much.",
        "love": "If you are able to host a small party, or even invite a couple friends for coffee, then you might find that it turns into a regular kind of get-together. By enlarging your circle of friends and acquaintances you will discover the kind of love that is deeply meaningful, rather than the more superficial type. The love you are seeking is gradually drawing closer.",
        "money": "You may be whirling like a dervish, calling credit card companies, paying off balances, and cutting up old cards. Nice work! This same burst of energy will help you set a new financial course at this time in your life. But your workplace may need some adjusting. It's too early to leave, though. Try to make the best of it.",
    },
    {
        "id": "Capricorn",
        "range": "December 22 - January 19",
        "horoscopes": "Make sure that you finish everything completely today. Tie up every loose end with a neat little bow and polish it up for show. People who have a lot of power over your life will be reviewing your work, and you want make to make sure that they like what they see. It won't be difficult at all to impress them, but you'll have to double-check your work just in case. Your relationship with these people is good, but you can't take anything for granted.",
        "love": "Keep up the good work regarding your efforts at developing a new circle of friends, and a whole new set of interests. You will be given more of an opportunity to help out in whatever capacity feels good to you. You love being of service to others, and needless to say you are more likely to find romance in this setting than anywhere else.",
        "money": "You're experiencing an energetic boost to your finances. You're very creative about coming up with new ideas for how to bring money into your life. You may have new concepts for a side business or just innovative, low-cost ways to advertise what you do. The planets support these efforts in a big way. You're on top of the world!",
    },
    {
        "id": "Gemini",
        "range": "May 21 - June 21",
        "horoscopes": "Just because you say goodbye to someone doesn't mean that they still can't inspire or affect your future in a positive way. You take them with you wherever you go, and they'll always be a part of you. Try to switch from sadness to gratitude that you got to know them in the first place. Your feelings are important to honor, but you can't let them control your goals in life. You can start to move again in a new direction.",
        "love": "You will feel the need to bring friends and other people into your immediate circle in order to work together on a project that is deeply meaningful and also of great help to others. It is through this kind of direct social action that you will encounter more opportunities for real love and romance. When you are working on behalf of others, you attract the best to yourself.",
        "money": "You're a bit restricted in your career this week. Not only may your work evaporate (just a little) but you could also be called upon to shoulder more of the burden. The universe is asking that you become more responsible and authoritative in this area. Your relationships may need to be developed further before they can deliver what you want and need from them financially.",
    },
    {
        "id": "Leo",
        "range": "July 23 - August 22",
        "horoscopes": "There is a new closeness growing between you and a relative. The nurturing aspect of your family life is much more predominant than usual right now, and it's something that can really help you deal with any drama you've been working through. This is a time of personal growth for you, when you can take the advice given to you by people who care about you and make good use of it. So make sure you open up in any conversations and let it all out.",
        "love": "There is a lot of enthusiasm and determination around today. Romance and relationships are open to clear communication. Ideas are flowing, and it may benefit you both to host a small party or social gathering at your home and invite a couple new people if that’s at all possible. This will open up your social life and also bring some new energy into your own relationship.",
        "money": "You may have some serious thinking to do this week about other people's money, or debt. Adopting a responsible attitude is best as you take stock of what you owe, negotiate a realistic payoff picture, and stick to it. Aspects indicate that your family and kids may be the biggest drain on your finances now. Strive for balance as you adhere to your budget.",
    },
    {
        "id": "Libra",
        "range": "September 23 - October 22",
        "horoscopes": `You need to be patient if you want closure in an ongoing dispute. It probably isn't coming any time soon, in part because the other person or people involved are nowhere near admitting to the extent of the role they've played in it. Instead of wondering what you can do to affect the actions of other people (which is nothing, really), focus on yourself. Have a "me" day soon and do only things that you want to do.`,
        "love": "Changes in your social status come through having the courage to move in new circles. Not that you usually have any problem with this. But we can all get stuck in a rut, and it wouldn't hurt to change your routine in this respect. It is a good time to get involved in some new activities, as this will boost your romantic life enormously.",
        "money": "For you, this week is about self-expression. You can be very creative, so you may be tempted to try harder with your wardrobe or go for a radical change of look. Aspects affecting beauty and affection mean that your family, romantic partner, or kids are right behind you on your financial and personal goals. It's good to know you have a supportive team.",
    },
    {
        "id": "Pisces",
        "range": "Fabruary 19 - March 20",
        "horoscopes": `If you're dealing with any contracts or other legal documents today, you need to be twice as meticulous as usual. Your energy could be low now, and it might be difficult for you to concentrate for any length of time. You run the risk of missing a few of the smaller details. Read the fine print very carefully, because that is where the big mistakes hide. You might need to take extra time to do a lot of things today, so plan accordingly.`,
        "love": "You will feel the need to bring friends and other people into your immediate circle in order to work together on a project that is deeply meaningful and also of great help to others. It is through this kind of direct social action that you will encounter more opportunities for real love and romance. When you are working on behalf of others, you attract the best to your",
        "money": "Lucky energy regarding other people's money means you may benefit from shared property, investments, or an unexpected inheritance. This unleashes all sorts of good stuff in this area of your life. Other aspects affect past lives, dreams, and karma. Do unto others what you would have done unto you, financially speaking.",
    },
    {
        "id": "Sagittarius",
        "range": "November 22 - December 21",
        "horoscopes": "Someone who is lovable but also a little frustrating could make things a bit rocky for you and mess up your plans for the day. Their inflexibility is going to wreak havoc with your schedule and upset your daily routine. The good news is that it won't take long for you to come up with a backup plan that helps you work around the obstacles they've inadvertently created. Celebrate the fact that you can always find a way to get yourself back on track.",
        "love": "You may not be able to hide away in the shadows so much today, although you usually manage to keep a lot of your inner nature hidden. Someone special may be demanding to know how you feel about them, and you, as usual, are reluctant to let them know. If you want the relationship to continue, then you had better speak up.",
        "money": "Aspects affecting your communication sector may move you to reach out to someone - or many someones. Amid all your talking, e-mailing, and texting, there's the sudden urge to capture your experience for posterity. This is a great time to begin writing something new no matter what your passion. You've got it going on. With your social groups and networking, you could make it pay off big.",
    },
    {
        "id": "Scorpio",
        "range": "October 23 - November 21",
        "horoscopes": "Looking back on your life is a good idea right now. Rerunning the movie of your life will remind you of your successes and, more importantly, the lessons you've learned from your mistakes. You'll also notice a pattern of behavior that can help you move forward into your future in a healthier way. Your growing strength and positive self-esteem will ensure that the mistakes you made in the past won't be repeated.",
        "love": "Your romantic and social life is in for a real boost of energy. If you have been feeling in a rut lately, then this would be a good time to go to a virtual game night or to join in with some online group activities and become more closely involved with others. This brings the opportunity for love into your life. Give it a try!",
        "money": "Aspects affecting past lives, dreams, and karma release your most interesting, individualistic ideas. What may have been blocked by obstacles in the past becomes freer and easier to achieve now. Some of your best ideas may emerge from your subconscious. You're being asked to consider working from home or bring in extra money by using your home creatively. It's your call.",
    },
    {
        "id": "Taurus",
        "range": "April 20 - May 20",
        "horoscopes": "You're feeling sensitive about your finances right now. They could be out of sync with those of everyone you're socializing with, which could cause some tension when the talk turns to the next outing. Nevertheless, you should try to take extra care to save your money. Resist shopping or going out for the time being. There could be some unexpected expenses coming up, and you'll want to be able to pay them quickly and painlessly. Start pinching those pennies!",
        "love": "Although you prefer to spend time doing your duty, whether at home or at work, there comes a moment in life when duty isn't everything. Recently you have had the desire to cast away your usual image and be more adventurous. Let your hair down and get out there. It is about time that you had some real fun.",
        "money": "Your career sector expands, and you get noticed this week. There's a loving atmosphere at work. You're certain to find creative ideas flowing. Meanwhile, you have the ability to build on past successes by providing a supportive cast willing to take direction at work. If ever there was a week to be in charge, this is it. Make your needs and wants known and others will step up to meet them.",
    },
    {
        "id": "Virgo",
        "range": "Agust 23 - September 22",
        "horoscopes": "Sometimes you need to separate your unrealistic goals from the goals that you can actually accomplish. You could be setting yourself up for failure by aiming much too high. It's good to challenge yourself, but do you really have to think in such grand terms? Be more modest in your aims. Instead of being rich by a certain age, just set a realistic goal to save a certain amount of money each month. That's something you can accomplish and something that will make your ego healthier.",
        "love": "A lot of new ideas will flow today. You may feel more of an urge to communicate with new people and socialize. And will be more inspired to be doing something practical. Working as part of a team will be good for you and may also enable you to meet up with someone who would like to team up with you. Give it your best shot!",
        "money": "You feel lucky this week. Since the energy is so expansive, you will draw opportunities to earn more as long as you keep your eyes open. Meanwhile, a harmonious aspect affects your job. Off with the kid gloves! It's time to show them what you're made of and attract a salary commensurate with your abilities.",
    }
]